#!/bin/bash

# make:controller command library — used by bin/shellrest

cmd_make_controller() {
    if [ $# -eq 0 ]; then
        echo "Usage: shellrest make:controller <name> [singular]"
        echo "Examples:"
        echo "  shellrest make:controller products"
        echo "  shellrest make:controller categories category"
        return 1
    fi

    local name="$1"
    local singular="$2"
    local routes_dir="${_PROJECT_ROOT}/routes"
    local filepath="${routes_dir}/${name}.sh"

    if [ -z "$singular" ]; then
        singular="${name%s}"
        if [ "$singular" = "$name" ]; then
            echo "Warning: '$name' has no trailing 's', can't auto-derive a singular form." >&2
            echo "Pass one explicitly: shellrest make:controller $name <singular>" >&2
            return 1
        fi
    fi

    if [ -f "$filepath" ]; then
        echo "Error: route file already exists: $filepath" >&2
        return 1
    fi

    mkdir -p "$routes_dir"

    cat > "$filepath" << EOF
#!/bin/bash

# Controller: $name
# Generated by: shellrest make:controller $name $singular
#
# Backing table "$name" is not created automatically. Generate it with:
#   shellrest make:migration create_${name}_table $name
# Then adjust the fields below (currently a placeholder "name" column) to match your schema.

register_route "GET"    "/$name"           "get_$name"
register_route "POST"   "/$name"           "post_$name"
register_route "GET"    "/$name/{id}"      "get_$singular"
register_route "PUT"    "/$name/{id}"      "put_$singular"
register_route "DELETE" "/$name/{id}"      "delete_$singular"

get_$name() {
    local result
    result=\$(db_select "$name" "*")
    [ -z "\$result" ] && result="[]"
    http_response "200 OK" "application/json" "\$result"
}

get_$singular() {
    local id="\$1"
    validate_path_param "\$id" || return
    local result
    result=\$(db_select "$name" "*" "id = \$id")
    if [ -z "\$result" ] || [ "\$result" = "[]" ]; then
        http_response "404 Not Found" "application/json" "\$(json_error "$singular not found")"
    else
        http_response "200 OK" "application/json" "\$result"
    fi
}

post_$name() {
    local body="\$1"

    # TODO: adjust required fields to match your schema
    if ! validate_required_fields "\$body" "name"; then
        http_response "400 Bad Request" "application/json" "\$(json_error "name is required")"
        return
    fi

    local name_field
    name_field=\$(get_json_field "\$body" "name")

    local id
    id=\$(db_insert "$name" "name" "\$(safe_sql_string "\$name_field")")
    http_response "201 Created" "application/json" \\
        "\$(db_select "$name" "*" "id = \$id")"
}

put_$singular() {
    local id="\$1" body="\$2"
    validate_path_param "\$id" || return

    # TODO: adjust required fields to match your schema
    if ! validate_required_fields "\$body" "name"; then
        http_response "400 Bad Request" "application/json" "\$(json_error "name is required")"
        return
    fi

    local name_field
    name_field=\$(get_json_field "\$body" "name")

    local changes
    changes=\$(db_update "$name" "name = \$(safe_sql_string "\$name_field")" "id = \$id")
    if [ "\${changes:-0}" -gt 0 ]; then
        http_response "200 OK" "application/json" "\$(db_select "$name" "*" "id = \$id")"
    else
        http_response "404 Not Found" "application/json" "\$(json_error "$singular not found")"
    fi
}

delete_$singular() {
    local id="\$1"
    validate_path_param "\$id" || return
    local changes
    changes=\$(db_delete "$name" "id = \$id")
    if [ "\${changes:-0}" -gt 0 ]; then
        http_response "204 No Content" "application/json" ""
    else
        http_response "404 Not Found" "application/json" "\$(json_error "$singular not found")"
    fi
}
EOF

    echo "Controller created: $filepath"
    echo ""
    echo "Routes are loaded fresh on every request — no server restart needed."
    echo "Don't forget to create the backing table:"
    echo "  shellrest make:migration create_${name}_table $name"
}
