name: Tests

on:
  push:
  pull_request:

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bats jq sqlite3

      - name: Run tests
        run: bats test/unit
